bugfix(ruby3): use File.exist? instead of File.exists?
Starting from Ruby 3.2.0, the exists? (pluralized) alias was removed.

After this version, you need to use the singular-form exist?

Examples:

rvm use 3.1.3

3.1.3 :001 > File.exist?("xyz")
=> false

3.1.3 :002 > File.exists?("xyz")
=> false

rvm use 3.2.0

3.2.0 :001 > File.exist?("xyz")
=> false

3.2.0 :002 > File.exists?("xyz")
(irb):2:in `<main>': undefined method `exists?' for File:Class (NoMethodError)